# Generated by Django 6.0.2 on 2026-02-06 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('read', 'Read'), ('reading', 'Reading'), ('plan_to_read', 'Plan to Read'), ('on_hold', 'On Hold'), ('dropped', 'Dropped')], max_length=15)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
