# Generated by Django 6.0.2 on 2026-02-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookmark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
