# Generated by Django 6.0.2 on 2026-02-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_bookmark_book_end_date_book_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookmark',
            field=models.IntegerField(),
        ),
    ]
