# Generated by Django 6.0.2 on 2026-02-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookmark',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
