# Generated by Django 6.0.2 on 2026-02-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='start_date',
        ),
    ]
