# Generated by Django 6.0.2 on 2026-02-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_end_date_remove_book_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('reading', 'Reading'), ('plan to read', 'Plan to Read'), ('on hold', 'On Hold'), ('dropped', 'Dropped')], max_length=15),
        ),
    ]
